In [1]:
import numpy as np

In [2]:
with open('LeapData', 'r') as f:
    content = f.readlines()
content = [x.strip() for x in content]
content

['1558107922.84|0.0|',
 '1558107922.92|1558107922.91|4989869|1558107922907701|0|0|0|0|',
 '1558107922.95|1558107922.95|4989870|1558107922941023|0|0|0|0|',
 '1558107922.99|1558107922.98|4989871|1558107922974343|0|0|0|0|',
 '1558107923.02|1558107923.01|4989872|1558107923007642|0|0|0|0|',
 '1558107923.05|1558107923.05|4989873|1558107923040959|0|0|0|0|',
 '1558107923.08|1558107923.08|4989874|1558107923074285|0|0|0|0|',
 '1558107923.12|1558107923.11|4989875|1558107923107543|0|0|0|0|',
 '1558107923.16|1558107923.15|4989876|1558107923140898|0|0|0|0|',
 '1558107923.19|1558107923.18|4989877|1558107923174144|0|0|0|0|',
 '1558107923.22|1558107923.21|4989878|1558107923207485|0|0|0|0|',
 '1558107923.25|1558107923.25|4989879|1558107923240767|0|0|0|0|',
 '1558107923.28|1558107923.28|4989880|1558107923274186|0|0|0|0|',
 '1558107923.32|1558107923.31|4989881|1558107923307414|0|0|0|0|',
 '1558107923.36|1558107923.35|4989882|1558107923340737|0|0|0|0|',
 '1558107923.39|1558107923.38|4989883|155810792337409

In [3]:
def to_nparray(string_co):
    string_co = string_co[1:]
    string_co = string_co[:-1]
    string_co = string_co.replace(" ", "")
    string_arr = string_co.split(',')
    return np.array([float(string_arr[0]), float(string_arr[1]), float(string_arr[2])])

In [4]:
hand = {}
index_palm_position = 10
index_wrist_position = 15
index_elbow_position = 16

index_thumb_m_prev = 21
index_thumb_m_next = 22
index_thumb_p_prev = 25
index_thumb_p_next = 26
index_thumb_i_prev = 29
index_thumb_i_next = 30
index_thumb_d_prev = 33
index_thumb_d_next = 34

index_index_m_prev = 40
index_index_m_next = 41
index_index_p_prev = 44
index_index_p_next = 45
index_index_i_prev = 48
index_index_i_next = 49
index_index_d_prev = 52
index_index_d_next = 53

index_middle_m_prev = 59
index_middle_m_next = 60
index_middle_p_prev = 63
index_middle_p_next = 64
index_middle_i_prev = 67
index_middle_i_next = 68
index_middle_d_prev = 71
index_middle_d_next = 72

index_ring_m_prev = 78
index_ring_m_next = 79
index_ring_p_prev = 82
index_ring_p_next = 83
index_ring_i_prev = 86
index_ring_i_next = 87
index_ring_d_prev = 90
index_ring_d_next = 91

index_pinky_m_prev = 97
index_pinky_m_next = 98
index_pinky_p_prev = 101
index_pinky_p_next = 102
index_pinky_i_prev = 105
index_pinky_i_next = 106
index_pinky_d_prev = 109
index_pinky_d_next = 110

palm_position = []
wrist_position = []
elbow_position = []
thumb_m_prev = []
thumb_m_next = []
thumb_p_prev = []
thumb_p_next = []
thumb_i_prev = []
thumb_i_next = []
thumb_d_prev = []
thumb_d_next = []

index_m_prev = []
index_m_next = []
index_p_prev = []
index_p_next = []
index_i_prev = []
index_i_next = []
index_d_prev = []
index_d_next = []

middle_m_prev = []
middle_m_next = []
middle_p_prev = []
middle_p_next = []
middle_i_prev = []
middle_i_next = []
middle_d_prev = []
middle_d_next = []

ring_m_prev = []
ring_m_next = []
ring_p_prev = []
ring_p_next = []
ring_i_prev = []
ring_i_next = []
ring_d_prev = []
ring_d_next = []

pinky_m_prev = []
pinky_m_next = []
pinky_p_prev = []
pinky_p_next = []
pinky_i_prev = []
pinky_i_next = []
pinky_d_prev = []
pinky_d_next = []

timestamp = []
for each_line in content:
    data = each_line.split('|')
    print(len(data))
    if(len(data) > 9):
#         print(data[10])
        data_save = data
        palm_position.append(to_nparray(data[index_palm_position]))
        wrist_position.append(to_nparray(data[index_wrist_position]))
        elbow_position.append(to_nparray(data[index_elbow_position] ))
        
        thumb_m_prev.append(to_nparray(data[index_thumb_m_prev]))
        thumb_m_next.append(to_nparray(data[index_thumb_m_next]))
        thumb_p_prev.append(to_nparray(data[index_thumb_p_prev]))
        thumb_p_next.append(to_nparray(data[index_thumb_p_next]))
        thumb_i_prev.append(to_nparray(data[index_thumb_i_prev]))
        thumb_i_next.append(to_nparray(data[index_thumb_i_next]))
        thumb_d_prev.append(to_nparray(data[index_thumb_d_prev]))
        thumb_d_next.append(to_nparray(data[index_thumb_d_next]))
        
        index_m_prev.append(to_nparray(data[index_index_m_prev]))
        index_m_next.append(to_nparray(data[index_index_m_next]))
        index_p_prev.append(to_nparray(data[index_index_p_prev]))
        index_p_next.append(to_nparray(data[index_index_p_next]))
        index_i_prev.append(to_nparray(data[index_index_i_prev]))
        index_i_next.append(to_nparray(data[index_index_i_next]))
        index_d_prev.append(to_nparray(data[index_index_d_prev]))
        index_d_next.append(to_nparray(data[index_index_d_next]))
        
        middle_m_prev.append(to_nparray(data[index_middle_m_prev]))
        middle_m_next.append(to_nparray(data[index_middle_m_next]))
        middle_p_prev.append(to_nparray(data[index_middle_p_prev]))
        middle_p_next.append(to_nparray(data[index_middle_p_next]))
        middle_i_prev.append(to_nparray(data[index_middle_i_prev]))
        middle_i_next.append(to_nparray(data[index_middle_i_next]))
        middle_d_prev.append(to_nparray(data[index_middle_d_prev]))
        middle_d_next.append(to_nparray(data[index_middle_d_next]))
        
        ring_m_prev.append(to_nparray(data[index_ring_m_prev]))
        ring_m_next.append(to_nparray(data[index_ring_m_next]))
        ring_p_prev.append(to_nparray(data[index_ring_p_prev]))
        ring_p_next.append(to_nparray(data[index_ring_p_next]))
        ring_i_prev.append(to_nparray(data[index_ring_i_prev]))
        ring_i_next.append(to_nparray(data[index_ring_i_next]))
        ring_d_prev.append(to_nparray(data[index_ring_d_prev]))
        ring_d_next.append(to_nparray(data[index_ring_d_next]))
        
        pinky_m_prev.append(to_nparray(data[index_pinky_m_prev]))
        pinky_m_next.append(to_nparray(data[index_pinky_m_next]))
        pinky_p_prev.append(to_nparray(data[index_pinky_p_prev]))
        pinky_p_next.append(to_nparray(data[index_pinky_p_next]))
        pinky_i_prev.append(to_nparray(data[index_pinky_i_prev]))
        pinky_i_next.append(to_nparray(data[index_pinky_i_next]))
        pinky_d_prev.append(to_nparray(data[index_pinky_d_prev]))
        pinky_d_next.append(to_nparray(data[index_pinky_d_next]))
        
        timestamp.append(data[0])
        
thumb_d_prev

3
9
9
9
9
9
9
9
9
9
9
9
9
9
9
9
9
9
9
9
9
9
9
9
9
9
9
9
9
9
9
9
9
9
9
9
9
9
9
9
9
9
9
9
9
9
9
9
9
9
9
9
9
9
9
9
9
9
9
9
9
9
9
9
9
9
9
9
9
9
9
9
9
9
9
9
9
9
9
9
9
9
9
9
9
9
9
9
9
9
9
9
9
9
9
9
9
9
9
9
9
9
9
9
9
9
9
9
9
9
9
9
9
9
9
9
9
9
9
9
9
9
9
9
9
9
9
9
9
9
9
9
9
9
9
9
9
9
9
9
9
9
9
9
9
9
9
9
9
9
9
9
9
9
9
9
9
9
9
9
9
9
9
9
9
9
9
9
9
9
9
9
9
9
9
9
9
9
9
9
9
9
9
9
9
9
9
9
9
9
9
9
9
9
9
9
9
9
9
9
9
9
9
9
9
9
9
9
9
9
9
9
9
9
9
9
9
9
9
9
9
9
9
9
9
9
9
9
9
9
9
9
9
9
9
9
9
9
9
9
9
9
9
9
9
9
9
9
9
9
9
9
9
9
9
9
9
9
9
9
9
9
9
9
9
9
9
9
9
9
9
9
9
9
9
9
9
9
9
9
9
9
9
9
9
9
9
9
9
9
9
9
9
9
9
9
9
9
9
9
9
9
9
9
9
9
9
9
9
9
9
9
9
9
9
9
9
9
9
9
9
9
9
9
9
9
9
9
9
9
9
9
9
9
9
9
9
9
9
9
9
9
9
9
9
9
9
9
9
9
9
9
9
9
9
9
9
9
9
9
9
9
9
9
9
9
9
9
9
9
9
9
9
9
9
9
9
9
9
9
9
9
9
9
9
9
9
9
9
9
9
9
9
9
9
9
9
9
9
9
9
9
9
9
9
9
9
9
9
9
9
9
9
9
9
9
9
9
9
9
9
9
9
9
9
9
9
9
9
9
9
9
9
113
113
113
113
113
113
113
113
113
113
113
113
113
113
113
113
113
113
113
113
113
113
113
113
113
113
113
113
113
113
113
113
113
11

[array([  7.83358, 155.614  ,  24.0883 ]),
 array([  7.87543, 155.732  ,  23.8888 ]),
 array([  7.97286, 155.919  ,  23.4485 ]),
 array([  7.89932, 156.378  ,  22.7943 ]),
 array([  8.1415, 156.606 ,  22.4321]),
 array([ 12.1855, 155.984 ,  21.4428]),
 array([ 14.7151, 155.548 ,  21.296 ]),
 array([ 16.4062, 155.242 ,  21.2837]),
 array([ 17.5808, 154.614 ,  21.8513]),
 array([ 18.3688, 155.364 ,  22.9653]),
 array([ 16.8817, 155.902 ,  22.4282]),
 array([  8.5022, 155.585 ,  23.0228]),
 array([ -6.00931, 158.573  ,  34.1184 ]),
 array([-10.2119, 158.127 ,  45.9879]),
 array([-10.7008, 158.557 ,  47.5396]),
 array([-19.031 , 163.314 ,  58.0618]),
 array([ 12.8264, 174.691 ,  64.2013]),
 array([ 26.145 , 204.817 ,  69.2946]),
 array([ 26.8731, 206.181 ,  69.7379]),
 array([ 26.954 , 209.507 ,  68.9732]),
 array([ 25.8949, 210.395 ,  68.1882]),
 array([ 22.6707, 214.237 ,  67.6414]),
 array([ 21.6515, 215.296 ,  67.1983]),
 array([ 20.5796, 216.724 ,  66.8874]),
 array([ 18.8636, 218.051

In [5]:
# palm_string
# palm_string.split(',')
# palm_position[0]
# float(palm_arr[0])
# data[index_index_m_prev]
data_save

['1558108554.09',
 '1558108554.09',
 '5022849',
 '1558108554089180',
 '1',
 '5',
 '0',
 '0',
 'Right hand',
 '326',
 '(-10.2289, 39.932, 110.459)',
 '35.491155738',
 '-58.4420566927',
 '-28.8029183114',
 '(-0.812413, 0.104007, -0.573732)',
 '(12.5865, 14.5622, 138.414)',
 '(189.448, -8.08006, 263.315)',
 'Thumb',
 '3260',
 '16.3274536133',
 'Metacarpal',
 '(-1.41658, 23.9443, 156.516)',
 '(-1.41658, 23.9443, 156.516)',
 '(0, 0, 0)',
 'Proximal',
 '(-1.41658, 23.9443, 156.516)',
 '(-31.014, 45.6537, 140.005)',
 '(0.735372, -0.539388, 0.41023)',
 'Intermediate',
 '(-31.014, 45.6537, 140.005)',
 '(-50.2972, 63.7715, 132.544)',
 '(0.701434, -0.659042, 0.271392)',
 'Distal',
 '(-50.2972, 63.7715, 132.544)',
 '(-62.3213, 78.1646, 130.46)',
 '(0.6372, -0.762742, 0.110453)',
 'Index',
 '3261',
 '15.5959844589',
 'Metacarpal',
 '(10.6226, 32.3786, 144.301)',
 '(-23.7887, 65.029, 108.684)',
 '(0.580107, -0.550424, 0.600424)',
 'Proximal',
 '(-23.7887, 65.029, 108.684)',
 '(-54.1783, 64.1576, 92.

In [6]:
# from matplotlib import pyplot
# from mpl_toolkits.mplot3d import Axes3D
# %matplotlib notebook
# fig = pyplot.figure()
# ax = Axes3D(fig)

# ax.scatter(palm_position[0][0], palm_position[0][1], palm_position[0][2], color = 'b')
# ax.scatter(wrist_position[0][0], wrist_position[0][1], wrist_position[0][2], color = 'c')

# thumb_x = [thumb_m_prev[0][0], thumb_m_next[0][0], thumb_p_prev[0][0], thumb_p_next[0][0], thumb_i_prev[0][0], thumb_i_next[0][0], thumb_d_prev[0][0], thumb_d_next[0][0]]
# thumb_y = [thumb_m_prev[0][1], thumb_m_next[0][1], thumb_p_prev[0][1], thumb_p_next[0][1], thumb_i_prev[0][1], thumb_i_next[0][1], thumb_d_prev[0][1], thumb_d_next[0][1]]
# thumb_z = [thumb_m_prev[0][2], thumb_m_next[0][2], thumb_p_prev[0][2], thumb_p_next[0][2], thumb_i_prev[0][2], thumb_i_next[0][2], thumb_d_prev[0][2], thumb_d_next[0][2]]
# k = 0
# for x,y,z in zip(thumb_x, thumb_y, thumb_z):
#     if(k == 0):
#         ax.scatter(x, y, z, marker = 'v', color = 'r')
#         k = -1
#     else:
#         ax.scatter(x, y, z, marker = '^', color = 'r')
# ax.plot(thumb_x, thumb_y, thumb_z, color = 'r')

# index_x = [index_m_prev[0][0], index_m_next[0][0], index_p_prev[0][0], index_p_next[0][0], index_i_prev[0][0], index_i_next[0][0], index_d_prev[0][0], index_d_next[0][0]]
# index_y = [index_m_prev[0][1], index_m_next[0][1], index_p_prev[0][1], index_p_next[0][1], index_i_prev[0][1], index_i_next[0][1], index_d_prev[0][1], index_d_next[0][1]]
# index_z = [index_m_prev[0][2], index_m_next[0][2], index_p_prev[0][2], index_p_next[0][2], index_i_prev[0][2], index_i_next[0][2], index_d_prev[0][2], index_d_next[0][2]]
# k = 0
# for x,y,z in zip(index_x, index_y, index_z):
#     if(k == 0):
#         ax.scatter(x, y, z, marker = 'v', color = 'm')
#         k = -1
#     else:
#         ax.scatter(x, y, z, marker = 'x', color = 'm')
# ax.plot(index_x, index_y, index_z, color = 'm')

# middle_x = [middle_m_prev[0][0], middle_m_next[0][0], middle_p_prev[0][0], middle_p_next[0][0], middle_i_prev[0][0], middle_i_next[0][0], middle_d_prev[0][0], middle_d_next[0][0]]
# middle_y = [middle_m_prev[0][1], middle_m_next[0][1], middle_p_prev[0][1], middle_p_next[0][1], middle_i_prev[0][1], middle_i_next[0][1], middle_d_prev[0][1], middle_d_next[0][1]]
# middle_z = [middle_m_prev[0][2], middle_m_next[0][2], middle_p_prev[0][2], middle_p_next[0][2], middle_i_prev[0][2], middle_i_next[0][2], middle_d_prev[0][2], middle_d_next[0][2]]
# k = 0
# for x,y,z in zip(middle_x, middle_y, middle_z):
#     if(k == 0):
#         ax.scatter(x, y, z, marker = 'v', color = 'y')
#         k = -1
#     else:
#         ax.scatter(x, y, z, marker = '*', color = 'y')
# ax.plot(middle_x, middle_y, middle_z, color = 'y')

# ring_x = [ring_m_prev[0][0], ring_m_next[0][0], ring_p_prev[0][0], ring_p_next[0][0], ring_i_prev[0][0], ring_i_next[0][0], ring_d_prev[0][0], ring_d_next[0][0]]
# ring_y = [ring_m_prev[0][1], ring_m_next[0][1], ring_p_prev[0][1], ring_p_next[0][1], ring_i_prev[0][1], ring_i_next[0][1], ring_d_prev[0][1], ring_d_next[0][1]]
# ring_z = [ring_m_prev[0][2], ring_m_next[0][2], ring_p_prev[0][2], ring_p_next[0][2], ring_i_prev[0][2], ring_i_next[0][2], ring_d_prev[0][2], ring_d_next[0][2]]
# k = 0
# for x,y,z in zip(ring_x, ring_y, ring_z):
#     if(k == 0):
#         ax.scatter(x, y, z, marker = 'v', color = 'g')
#         k = -1
#     ax.scatter(x, y, z, marker = '+', color = 'g')
# ax.plot(ring_x, ring_y, ring_z, color = 'g')

# pinky_x = [pinky_m_prev[0][0], pinky_m_next[0][0], pinky_p_prev[0][0], pinky_p_next[0][0], pinky_i_prev[0][0], pinky_i_next[0][0], pinky_d_prev[0][0], pinky_d_next[0][0]]
# pinky_y = [pinky_m_prev[0][1], pinky_m_next[0][1], pinky_p_prev[0][1], pinky_p_next[0][1], pinky_i_prev[0][1], pinky_i_next[0][1], pinky_d_prev[0][1], pinky_d_next[0][1]]
# pinky_z = [pinky_m_prev[0][2], pinky_m_next[0][2], pinky_p_prev[0][2], pinky_p_next[0][2], pinky_i_prev[0][2], pinky_i_next[0][2], pinky_d_prev[0][2], pinky_d_next[0][2]]
# k = 0
# for x,y,z in zip(pinky_x, pinky_y, pinky_z):
#     if(k == 0):
#         ax.scatter(x, y, z, marker = 'v', color = 'k')
#         k = -1
#     ax.scatter(x, y, z, marker = 'D', color = 'k')
# ax.plot(pinky_x, pinky_y, pinky_z, color = 'k')

# for angle in range(0, 360):
#     ax.view_init(30, angle)
#     plt.draw()
#     plt.pause(.001)
# pyplot.show()

In [7]:
from matplotlib import pyplot
from mpl_toolkits.mplot3d import Axes3D
# %matplotlib notebook

for i in range(len(index_p_prev)):
    fig = pyplot.figure()
    ax = Axes3D(fig)
    
    ax.scatter(palm_position[i][0], palm_position[i][1], palm_position[i][2], color = 'b')
    ax.scatter(wrist_position[i][0], wrist_position[i][1], wrist_position[i][2], color = 'c')
#     ax.scatter(elbow_position[i][0], elbow_position[i][1], elbow_position[i][2], color = 'c')

    thumb_x = [thumb_m_prev[i][0], thumb_m_next[i][0], thumb_p_prev[i][0], thumb_p_next[i][0], thumb_i_prev[i][0], thumb_i_next[i][0], thumb_d_prev[i][0], thumb_d_next[i][0]]
    thumb_y = [thumb_m_prev[i][1], thumb_m_next[i][1], thumb_p_prev[i][1], thumb_p_next[i][1], thumb_i_prev[i][1], thumb_i_next[i][1], thumb_d_prev[i][1], thumb_d_next[i][1]]
    thumb_z = [thumb_m_prev[i][2], thumb_m_next[i][2], thumb_p_prev[i][2], thumb_p_next[i][2], thumb_i_prev[i][2], thumb_i_next[i][2], thumb_d_prev[i][2], thumb_d_next[i][2]]
    k = 0
    for x,y,z in zip(thumb_x, thumb_y, thumb_z):
        if(k == 0):
            ax.scatter(x, y, z, marker = 'v', color = 'r')
            k = -1
        else:
            ax.scatter(x, y, z, marker = '^', color = 'r')
    ax.plot(thumb_x, thumb_y, thumb_z, color = 'r')

    index_x = [index_m_prev[i][0], index_m_next[i][0], index_p_prev[i][0], index_p_next[i][0], index_i_prev[i][0], index_i_next[i][0], index_d_prev[i][0], index_d_next[i][0]]
    index_y = [index_m_prev[i][1], index_m_next[i][1], index_p_prev[i][1], index_p_next[i][1], index_i_prev[i][1], index_i_next[i][1], index_d_prev[i][1], index_d_next[i][1]]
    index_z = [index_m_prev[i][2], index_m_next[i][2], index_p_prev[i][2], index_p_next[i][2], index_i_prev[i][2], index_i_next[i][2], index_d_prev[i][2], index_d_next[i][2]]
    k = 0
    for x,y,z in zip(index_x, index_y, index_z):
        if(k == 0):
            ax.scatter(x, y, z, marker = 'v', color = 'm')
            k = -1
        else:
            ax.scatter(x, y, z, marker = 'x', color = 'm')
    ax.plot(index_x, index_y, index_z, color = 'm')

    middle_x = [middle_m_prev[i][0], middle_m_next[i][0], middle_p_prev[i][0], middle_p_next[i][0], middle_i_prev[i][0], middle_i_next[i][0], middle_d_prev[i][0], middle_d_next[i][0]]
    middle_y = [middle_m_prev[i][1], middle_m_next[i][1], middle_p_prev[i][1], middle_p_next[i][1], middle_i_prev[i][1], middle_i_next[i][1], middle_d_prev[i][1], middle_d_next[i][1]]
    middle_z = [middle_m_prev[i][2], middle_m_next[i][2], middle_p_prev[i][2], middle_p_next[i][2], middle_i_prev[i][2], middle_i_next[i][2], middle_d_prev[i][2], middle_d_next[i][2]]
    k = 0
    for x,y,z in zip(middle_x, middle_y, middle_z):
        if(k == 0):
            ax.scatter(x, y, z, marker = 'v', color = 'y')
            k = -1
        else:
            ax.scatter(x, y, z, marker = '*', color = 'y')
    ax.plot(middle_x, middle_y, middle_z, color = 'y')

    ring_x = [ring_m_prev[i][0], ring_m_next[i][0], ring_p_prev[i][0], ring_p_next[i][0], ring_i_prev[i][0], ring_i_next[i][0], ring_d_prev[i][0], ring_d_next[i][0]]
    ring_y = [ring_m_prev[i][1], ring_m_next[i][1], ring_p_prev[i][1], ring_p_next[i][1], ring_i_prev[i][1], ring_i_next[i][1], ring_d_prev[i][1], ring_d_next[i][1]]
    ring_z = [ring_m_prev[i][2], ring_m_next[i][2], ring_p_prev[i][2], ring_p_next[i][2], ring_i_prev[i][2], ring_i_next[i][2], ring_d_prev[i][2], ring_d_next[i][2]]
    k = 0
    for x,y,z in zip(ring_x, ring_y, ring_z):
        if(k == 0):
            ax.scatter(x, y, z, marker = 'v', color = 'g')
            k = -1
        ax.scatter(x, y, z, marker = '+', color = 'g')
    ax.plot(ring_x, ring_y, ring_z, color = 'g')

    pinky_x = [pinky_m_prev[i][0], pinky_m_next[i][0], pinky_p_prev[i][0], pinky_p_next[i][0], pinky_i_prev[i][0], pinky_i_next[i][0], pinky_d_prev[i][0], pinky_d_next[i][0]]
    pinky_y = [pinky_m_prev[i][1], pinky_m_next[i][1], pinky_p_prev[i][1], pinky_p_next[i][1], pinky_i_prev[i][1], pinky_i_next[i][1], pinky_d_prev[i][1], pinky_d_next[i][1]]
    pinky_z = [pinky_m_prev[i][2], pinky_m_next[i][2], pinky_p_prev[i][2], pinky_p_next[i][2], pinky_i_prev[i][2], pinky_i_next[i][2], pinky_d_prev[i][2], pinky_d_next[i][2]]
    k = 0
    for x,y,z in zip(pinky_x, pinky_y, pinky_z):
        if(k == 0):
            ax.scatter(x, y, z, marker = 'v', color = 'k')
            k = -1
        ax.scatter(x, y, z, marker = 'D', color = 'k')
    ax.plot(pinky_x, pinky_y, pinky_z, color = 'k')
    pyplot.title(str(timestamp[i]))
    pyplot.savefig('visualisation/image_' + str(i) + '.jpg')
# for angle in range(0, 360):
#     ax.view_init(30, angle)
#     plt.draw()
#     plt.pause(.001)
# pyplot.show()

/home/saumya-shah/anaconda2/lib/python2.7/site-packages/matplotlib/pyplot.py:522: RuntimeWarning: More than 20 figures have been opened. Figures created through the pyplot interface (`matplotlib.pyplot.figure`) are retained until explicitly closed and may consume too much memory. (To control this warning, see the rcParam `figure.max_open_warning`).
  max_open_warning, RuntimeWarning)


In [8]:
# palm_position[0]
# data[30]
thumb_x

[-1.41658, -1.41658, -1.41658, -31.014, -31.014, -50.2972, -50.2972, -62.3213]

In [9]:
# for x,y,z in zip([1, 2], [3, 4], [5, 6]):
#     print(x);print(y);print(z);print('\n')
# middle_x
len(palm_position)

1343